version: '3.8'

services:
    mysqlserver:
      image: mysql:8.0
      ports:
      - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_USER=hbstudent
        - MYSQL_PASSWORD=hbstudent
        - MYSQL_DATABASE=employee_directory
      volumes:
        - mysql_data:/var/lib/mysql
        - mysql_config:/etc/mysql/conf.d
      networks:
        - springboot-mysql-net

    curd-application:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
          - SPRING_PROFILES_ACTIVE = docker
        depends_on:
            - mysqlserver
            - redis
        networks:
            - springboot-mysql-net

    redis:
      image: 'redis:latest'
      container_name: redis
      ports:
        - '6379:6379'
      volumes:
        - cache:/data
      networks:
        - springboot-mysql-net
      command: "redis-server"


networks:
  springboot-mysql-net:

volumes:
  mysql_data:
  mysql_config:
  cache:
